// Verified Tajweed metadata (Hafs/Uthmani).
//
// Annotations are [start, end) character spans generated by the
// cpfair/quran-tajweed decision trees (Dar al-Maarifah references)
// run against OUR EXACT bundled Tanzil text — alignment by
// construction, never hand-shifted. Rendering only colors spans;
// the underlying verse text is never altered.

import 'dart:convert';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../content/content_packages.dart';

class TajweedSpan {
  const TajweedSpan({
    required this.rule,
    required this.start,
    required this.end,
  });

  final String rule;
  final int start;
  final int end;
}

class TajweedRuleInfo {
  const TajweedRuleInfo({
    required this.rule,
    required this.nameAr,
    required this.nameEn,
    required this.colorValue,
  });

  final String rule;
  final String nameAr;
  final String nameEn;
  final int colorValue;
}

/// Canonical rule palette. Unknown rules from future datasets fall
/// back to grey rather than disappearing silently.
const List<TajweedRuleInfo> kTajweedRules = [
  TajweedRuleInfo(
      rule: 'ghunnah',
      nameAr: 'غنة',
      nameEn: 'Ghunnah',
      colorValue: 0xFF2E7D32),
  TajweedRuleInfo(
      rule: 'hamzat_wasl',
      nameAr: 'همزة الوصل',
      nameEn: 'Hamzat al-Wasl',
      colorValue: 0xFF9E9E9E),
  TajweedRuleInfo(
      rule: 'idghaam_ghunnah',
      nameAr: 'إدغام بغنة',
      nameEn: 'Idgham with Ghunnah',
      colorValue: 0xFFEF6C00),
  TajweedRuleInfo(
      rule: 'idghaam_no_ghunnah',
      nameAr: 'إدغام بغير غنة',
      nameEn: 'Idgham without Ghunnah',
      colorValue: 0xFFF9A825),
  TajweedRuleInfo(
      rule: 'idghaam_shafawi',
      nameAr: 'إدغام شفوي',
      nameEn: 'Idgham Shafawi',
      colorValue: 0xFFFB8C00),
  TajweedRuleInfo(
      rule: 'ikhfa',
      nameAr: 'إخفاء',
      nameEn: 'Ikhfa',
      colorValue: 0xFF00838F),
  TajweedRuleInfo(
      rule: 'ikhfa_shafawi',
      nameAr: 'إخفاء شفوي',
      nameEn: 'Ikhfa Shafawi',
      colorValue: 0xFF00ACC1),
  TajweedRuleInfo(
      rule: 'iqlab',
      nameAr: 'إقلاب',
      nameEn: 'Iqlab',
      colorValue: 0xFF6A1B9A),
  TajweedRuleInfo(
      rule: 'madd_2',
      nameAr: 'مد طبيعي',
      nameEn: 'Madd (2)',
      colorValue: 0xFF1565C0),
  TajweedRuleInfo(
      rule: 'madd_246',
      nameAr: 'مد جائز',
      nameEn: 'Madd (2/4/6)',
      colorValue: 0xFF1E88E5),
  TajweedRuleInfo(
      rule: 'madd_6',
      nameAr: 'مد لازم',
      nameEn: 'Madd (6)',
      colorValue: 0xFF0D47A1),
  TajweedRuleInfo(
      rule: 'qalqalah',
      nameAr: 'قلقلة',
      nameEn: 'Qalqalah',
      colorValue: 0xFFC62828),
  TajweedRuleInfo(
      rule: 'madd_muttasil',
      nameAr: 'مد متصل',
      nameEn: 'Madd Muttasil',
      colorValue: 0xFF0D47A1),
  TajweedRuleInfo(
      rule: 'madd_munfasil',
      nameAr: 'مد منفصل',
      nameEn: 'Madd Munfasil',
      colorValue: 0xFF42A5F5),
  TajweedRuleInfo(
      rule: 'lam_shamsiyyah',
      nameAr: 'لام شمسية',
      nameEn: 'Lam Shamsiyyah',
      colorValue: 0xFF78909C),
  TajweedRuleInfo(
      rule: 'silent',
      nameAr: 'حرف لا يُنطق',
      nameEn: 'Silent letter',
      colorValue: 0xFFBDBDBD),
  TajweedRuleInfo(
      rule: 'idghaam_mutajanisayn',
      nameAr: 'إدغام متجانسين',
      nameEn: 'Idgham Mutajanisayn',
      colorValue: 0xFFFF8F00),
  TajweedRuleInfo(
      rule: 'idghaam_mutaqaribayn',
      nameAr: 'إدغام متقاربين',
      nameEn: 'Idgham Mutaqaribayn',
      colorValue: 0xFFFFB300),
];

TajweedRuleInfo ruleInfo(String rule) =>
    kTajweedRules.where((r) => r.rule == rule).firstOrNull ??
    TajweedRuleInfo(
        rule: rule,
        nameAr: rule,
        nameEn: rule,
        colorValue: 0xFF757575);

/// Pure span builder: clamps out-of-range annotations defensively
/// (logged by tests) and never mutates text.
List<({int start, int end, String? rule})> buildTajweedSegments(
    String text, List<TajweedSpan> spans) {
  final points = <int>{0, text.length};
  for (final s in spans) {
    final a = s.start.clamp(0, text.length);
    final b = s.end.clamp(0, text.length);
    if (a < b) {
      points.add(a);
      points.add(b);
    }
  }
  final sorted = points.toList()..sort();
  final out = <({int start, int end, String? rule})>[];
  for (var i = 0; i < sorted.length - 1; i++) {
    final a = sorted[i];
    final b = sorted[i + 1];
    String? rule;
    for (final s in spans) {
      if (s.start <= a && b <= s.end) {
        rule = s.rule;
        break;
      }
    }
    out.add((start: a, end: b, rule: rule));
  }
  return out;
}

/// ayah → spans for one surah (Hafs/Uthmani Tajweed only).
final tajweedSurahProvider =
    FutureProvider.family<Map<int, List<TajweedSpan>>, int>(
        (ref, surah) async {
  ref.watch(contentRevisionProvider);
  try {
    if (!await ContentPackageStore.instance
        .isInstalled('quran:tajweed-hafs')) {
      return const {};
    }
    final raw = await ContentPackageStore.instance.loadString(
      'assets/quran/tajweed/hafs/$surah.json',
    );
    final json = jsonDecode(raw) as Map<String, dynamic>;
    final out = <int, List<TajweedSpan>>{};
    for (final e in (json['entries'] as List)) {
      final m = e as Map<String, dynamic>;
      out[(m['ayah'] as num).toInt()] = [
        for (final a in (m['annotations'] as List))
          TajweedSpan(
            rule: (a as Map<String, dynamic>)['rule'] as String,
            start: ((a)['start'] as num).toInt(),
            end: ((a)['end'] as num).toInt(),
          ),
      ];
    }
    return out;
  } catch (_) {
    return const {};
  }
});
