package com.godfather59.quransunnah.quran

// Full 114-surah metadata (factual, non-textual: names + counts +
// Makki/Madani). Ayah WORDING is never stored here.
// Ported from lib/data/seed/surah_metadata.dart.

val surahMetadata: List<SurahMeta> = listOf(
    SurahMeta(number = 1, nameAr = "الفاتحة", nameEn = "Al-Fatihah", nameFr = "Al-Fatiha", ayahCount = 7, makki = true),
    SurahMeta(number = 2, nameAr = "البقرة", nameEn = "Al-Baqarah", nameFr = "La Vache", ayahCount = 286, makki = false),
    SurahMeta(number = 3, nameAr = "آل عمران", nameEn = "Aal Imran", nameFr = "La Famille d’Imran", ayahCount = 200, makki = false),
    SurahMeta(number = 4, nameAr = "النساء", nameEn = "An-Nisa", nameFr = "Les Femmes", ayahCount = 176, makki = false),
    SurahMeta(number = 5, nameAr = "المائدة", nameEn = "Al-Ma’idah", nameFr = "La Table servie", ayahCount = 120, makki = false),
    SurahMeta(number = 6, nameAr = "الأنعام", nameEn = "Al-An‘am", nameFr = "Les Bestiaux", ayahCount = 165, makki = true),
    SurahMeta(number = 7, nameAr = "الأعراف", nameEn = "Al-A‘raf", nameFr = "Al-A‘raf", ayahCount = 206, makki = true),
    SurahMeta(number = 8, nameAr = "الأنفال", nameEn = "Al-Anfal", nameFr = "Le Butin", ayahCount = 75, makki = false),
    SurahMeta(number = 9, nameAr = "التوبة", nameEn = "At-Tawbah", nameFr = "Le Repentir", ayahCount = 129, makki = false),
    SurahMeta(number = 10, nameAr = "يونس", nameEn = "Yunus", nameFr = "Jonas", ayahCount = 109, makki = true),
    SurahMeta(number = 11, nameAr = "هود", nameEn = "Hud", nameFr = "Hud", ayahCount = 123, makki = true),
    SurahMeta(number = 12, nameAr = "يوسف", nameEn = "Yusuf", nameFr = "Joseph", ayahCount = 111, makki = true),
    SurahMeta(number = 13, nameAr = "الرعد", nameEn = "Ar-Ra‘d", nameFr = "Le Tonnerre", ayahCount = 43, makki = false),
    SurahMeta(number = 14, nameAr = "إبراهيم", nameEn = "Ibrahim", nameFr = "Abraham", ayahCount = 52, makki = true),
    SurahMeta(number = 15, nameAr = "الحجر", nameEn = "Al-Hijr", nameFr = "Al-Hijr", ayahCount = 99, makki = true),
    SurahMeta(number = 16, nameAr = "النحل", nameEn = "An-Nahl", nameFr = "Les Abeilles", ayahCount = 128, makki = true),
    SurahMeta(number = 17, nameAr = "الإسراء", nameEn = "Al-Isra", nameFr = "Le Voyage nocturne", ayahCount = 111, makki = true),
    SurahMeta(number = 18, nameAr = "الكهف", nameEn = "Al-Kahf", nameFr = "La Caverne", ayahCount = 110, makki = true),
    SurahMeta(number = 19, nameAr = "مريم", nameEn = "Maryam", nameFr = "Marie", ayahCount = 98, makki = true),
    SurahMeta(number = 20, nameAr = "طه", nameEn = "Ta-Ha", nameFr = "Ta-Ha", ayahCount = 135, makki = true),
    SurahMeta(number = 21, nameAr = "الأنبياء", nameEn = "Al-Anbiya", nameFr = "Les Prophètes", ayahCount = 112, makki = true),
    SurahMeta(number = 22, nameAr = "الحج", nameEn = "Al-Hajj", nameFr = "Le Pèlerinage", ayahCount = 78, makki = false),
    SurahMeta(number = 23, nameAr = "المؤمنون", nameEn = "Al-Mu’minun", nameFr = "Les Croyants", ayahCount = 118, makki = true),
    SurahMeta(number = 24, nameAr = "النور", nameEn = "An-Nur", nameFr = "La Lumière", ayahCount = 64, makki = false),
    SurahMeta(number = 25, nameAr = "الفرقان", nameEn = "Al-Furqan", nameFr = "Le Discernement", ayahCount = 77, makki = true),
    SurahMeta(number = 26, nameAr = "الشعراء", nameEn = "Ash-Shu‘ara", nameFr = "Les Poètes", ayahCount = 227, makki = true),
    SurahMeta(number = 27, nameAr = "النمل", nameEn = "An-Naml", nameFr = "Les Fourmis", ayahCount = 93, makki = true),
    SurahMeta(number = 28, nameAr = "القصص", nameEn = "Al-Qasas", nameFr = "Le Récit", ayahCount = 88, makki = true),
    SurahMeta(number = 29, nameAr = "العنكبوت", nameEn = "Al-‘Ankabut", nameFr = "L’Araignée", ayahCount = 69, makki = true),
    SurahMeta(number = 30, nameAr = "الروم", nameEn = "Ar-Rum", nameFr = "Les Romains", ayahCount = 60, makki = true),
    SurahMeta(number = 31, nameAr = "لقمان", nameEn = "Luqman", nameFr = "Luqman", ayahCount = 34, makki = true),
    SurahMeta(number = 32, nameAr = "السجدة", nameEn = "As-Sajdah", nameFr = "La Prosternation", ayahCount = 30, makki = true),
    SurahMeta(number = 33, nameAr = "الأحزاب", nameEn = "Al-Ahzab", nameFr = "Les Coalisés", ayahCount = 73, makki = false),
    SurahMeta(number = 34, nameAr = "سبأ", nameEn = "Saba", nameFr = "Saba", ayahCount = 54, makki = true),
    SurahMeta(number = 35, nameAr = "فاطر", nameEn = "Fatir", nameFr = "Le Créateur", ayahCount = 45, makki = true),
    SurahMeta(number = 36, nameAr = "يس", nameEn = "Ya-Sin", nameFr = "Ya-Sin", ayahCount = 83, makki = true),
    SurahMeta(number = 37, nameAr = "الصافات", nameEn = "As-Saffat", nameFr = "Les Rangés", ayahCount = 182, makki = true),
    SurahMeta(number = 38, nameAr = "ص", nameEn = "Sad", nameFr = "Sad", ayahCount = 88, makki = true),
    SurahMeta(number = 39, nameAr = "الزمر", nameEn = "Az-Zumar", nameFr = "Les Groupes", ayahCount = 75, makki = true),
    SurahMeta(number = 40, nameAr = "غافر", nameEn = "Ghafir", nameFr = "Le Pardonneur", ayahCount = 85, makki = true),
    SurahMeta(number = 41, nameAr = "فصلت", nameEn = "Fussilat", nameFr = "Les Versets détaillés", ayahCount = 54, makki = true),
    SurahMeta(number = 42, nameAr = "الشورى", nameEn = "Ash-Shura", nameFr = "La Consultation", ayahCount = 53, makki = true),
    SurahMeta(number = 43, nameAr = "الزخرف", nameEn = "Az-Zukhruf", nameFr = "L’Ornement", ayahCount = 89, makki = true),
    SurahMeta(number = 44, nameAr = "الدخان", nameEn = "Ad-Dukhan", nameFr = "La Fumée", ayahCount = 59, makki = true),
    SurahMeta(number = 45, nameAr = "الجاثية", nameEn = "Al-Jathiyah", nameFr = "L’Agenouillée", ayahCount = 37, makki = true),
    SurahMeta(number = 46, nameAr = "الأحقاف", nameEn = "Al-Ahqaf", nameFr = "Al-Ahqaf", ayahCount = 35, makki = true),
    SurahMeta(number = 47, nameAr = "محمد", nameEn = "Muhammad", nameFr = "Muhammad", ayahCount = 38, makki = false),
    SurahMeta(number = 48, nameAr = "الفتح", nameEn = "Al-Fath", nameFr = "La Victoire", ayahCount = 29, makki = false),
    SurahMeta(number = 49, nameAr = "الحجرات", nameEn = "Al-Hujurat", nameFr = "Les Appartements", ayahCount = 18, makki = false),
    SurahMeta(number = 50, nameAr = "ق", nameEn = "Qaf", nameFr = "Qaf", ayahCount = 45, makki = true),
    SurahMeta(number = 51, nameAr = "الذاريات", nameEn = "Adh-Dhariyat", nameFr = "Qui éparpillent", ayahCount = 60, makki = true),
    SurahMeta(number = 52, nameAr = "الطور", nameEn = "At-Tur", nameFr = "Le Mont", ayahCount = 49, makki = true),
    SurahMeta(number = 53, nameAr = "النجم", nameEn = "An-Najm", nameFr = "L’Étoile", ayahCount = 62, makki = true),
    SurahMeta(number = 54, nameAr = "القمر", nameEn = "Al-Qamar", nameFr = "La Lune", ayahCount = 55, makki = true),
    SurahMeta(number = 55, nameAr = "الرحمن", nameEn = "Ar-Rahman", nameFr = "Le Tout Miséricordieux", ayahCount = 78, makki = false),
    SurahMeta(number = 56, nameAr = "الواقعة", nameEn = "Al-Waqi‘ah", nameFr = "L’Événement", ayahCount = 96, makki = true),
    SurahMeta(number = 57, nameAr = "الحديد", nameEn = "Al-Hadid", nameFr = "Le Fer", ayahCount = 29, makki = false),
    SurahMeta(number = 58, nameAr = "المجادلة", nameEn = "Al-Mujadila", nameFr = "La Discussion", ayahCount = 22, makki = false),
    SurahMeta(number = 59, nameAr = "الحشر", nameEn = "Al-Hashr", nameFr = "L’Exode", ayahCount = 24, makki = false),
    SurahMeta(number = 60, nameAr = "الممتحنة", nameEn = "Al-Mumtahanah", nameFr = "L’Éprouvée", ayahCount = 13, makki = false),
    SurahMeta(number = 61, nameAr = "الصف", nameEn = "As-Saff", nameFr = "Le Rang", ayahCount = 14, makki = false),
    SurahMeta(number = 62, nameAr = "الجمعة", nameEn = "Al-Jumu‘ah", nameFr = "Le Vendredi", ayahCount = 11, makki = false),
    SurahMeta(number = 63, nameAr = "المنافقون", nameEn = "Al-Munafiqun", nameFr = "Les Hypocrites", ayahCount = 11, makki = false),
    SurahMeta(number = 64, nameAr = "التغابن", nameEn = "At-Taghabun", nameFr = "La Grande perte", ayahCount = 18, makki = false),
    SurahMeta(number = 65, nameAr = "الطلاق", nameEn = "At-Talaq", nameFr = "Le Divorce", ayahCount = 12, makki = false),
    SurahMeta(number = 66, nameAr = "التحريم", nameEn = "At-Tahrim", nameFr = "L’Interdiction", ayahCount = 12, makki = false),
    SurahMeta(number = 67, nameAr = "الملك", nameEn = "Al-Mulk", nameFr = "La Royauté", ayahCount = 30, makki = true),
    SurahMeta(number = 68, nameAr = "القلم", nameEn = "Al-Qalam", nameFr = "La Plume", ayahCount = 52, makki = true),
    SurahMeta(number = 69, nameAr = "الحاقة", nameEn = "Al-Haqqah", nameFr = "L’Inéluctable", ayahCount = 52, makki = true),
    SurahMeta(number = 70, nameAr = "المعارج", nameEn = "Al-Ma‘arij", nameFr = "Les Voies d’ascension", ayahCount = 44, makki = true),
    SurahMeta(number = 71, nameAr = "نوح", nameEn = "Nuh", nameFr = "Noé", ayahCount = 28, makki = true),
    SurahMeta(number = 72, nameAr = "الجن", nameEn = "Al-Jinn", nameFr = "Les Djinns", ayahCount = 28, makki = true),
    SurahMeta(number = 73, nameAr = "المزمل", nameEn = "Al-Muzzammil", nameFr = "L’Enveloppé", ayahCount = 20, makki = true),
    SurahMeta(number = 74, nameAr = "المدثر", nameEn = "Al-Muddaththir", nameFr = "Le Revêtu", ayahCount = 56, makki = true),
    SurahMeta(number = 75, nameAr = "القيامة", nameEn = "Al-Qiyamah", nameFr = "La Résurrection", ayahCount = 40, makki = true),
    SurahMeta(number = 76, nameAr = "الإنسان", nameEn = "Al-Insan", nameFr = "L’Homme", ayahCount = 31, makki = false),
    SurahMeta(number = 77, nameAr = "المرسلات", nameEn = "Al-Mursalat", nameFr = "Les Envoyés", ayahCount = 50, makki = true),
    SurahMeta(number = 78, nameAr = "النبأ", nameEn = "An-Naba", nameFr = "La Nouvelle", ayahCount = 40, makki = true),
    SurahMeta(number = 79, nameAr = "النازعات", nameEn = "An-Nazi‘at", nameFr = "Les Anges qui arrachent", ayahCount = 46, makki = true),
    SurahMeta(number = 80, nameAr = "عبس", nameEn = "‘Abasa", nameFr = "Il s’est renfrogné", ayahCount = 42, makki = true),
    SurahMeta(number = 81, nameAr = "التكوير", nameEn = "At-Takwir", nameFr = "L’Obscurcissement", ayahCount = 29, makki = true),
    SurahMeta(number = 82, nameAr = "الانفطار", nameEn = "Al-Infitar", nameFr = "La Rupture", ayahCount = 19, makki = true),
    SurahMeta(number = 83, nameAr = "المطففين", nameEn = "Al-Mutaffifin", nameFr = "Les Fraudeurs", ayahCount = 36, makki = true),
    SurahMeta(number = 84, nameAr = "الانشقاق", nameEn = "Al-Inshiqaq", nameFr = "La Déchirure", ayahCount = 25, makki = true),
    SurahMeta(number = 85, nameAr = "البروج", nameEn = "Al-Buruj", nameFr = "Les Constellations", ayahCount = 22, makki = true),
    SurahMeta(number = 86, nameAr = "الطارق", nameEn = "At-Tariq", nameFr = "L’Astre nocturne", ayahCount = 17, makki = true),
    SurahMeta(number = 87, nameAr = "الأعلى", nameEn = "Al-A‘la", nameFr = "Le Très-Haut", ayahCount = 19, makki = true),
    SurahMeta(number = 88, nameAr = "الغاشية", nameEn = "Al-Ghashiyah", nameFr = "L’Enveloppante", ayahCount = 26, makki = true),
    SurahMeta(number = 89, nameAr = "الفجر", nameEn = "Al-Fajr", nameFr = "L’Aube", ayahCount = 30, makki = true),
    SurahMeta(number = 90, nameAr = "البلد", nameEn = "Al-Balad", nameFr = "La Cité", ayahCount = 20, makki = true),
    SurahMeta(number = 91, nameAr = "الشمس", nameEn = "Ash-Shams", nameFr = "Le Soleil", ayahCount = 15, makki = true),
    SurahMeta(number = 92, nameAr = "الليل", nameEn = "Al-Layl", nameFr = "La Nuit", ayahCount = 21, makki = true),
    SurahMeta(number = 93, nameAr = "الضحى", nameEn = "Ad-Duha", nameFr = "Le Jour montant", ayahCount = 11, makki = true),
    SurahMeta(number = 94, nameAr = "الشرح", nameEn = "Ash-Sharh", nameFr = "L’Ouverture", ayahCount = 8, makki = true),
    SurahMeta(number = 95, nameAr = "التين", nameEn = "At-Tin", nameFr = "Le Figuier", ayahCount = 8, makki = true),
    SurahMeta(number = 96, nameAr = "العلق", nameEn = "Al-‘Alaq", nameFr = "L’Adhérence", ayahCount = 19, makki = true),
    SurahMeta(number = 97, nameAr = "القدر", nameEn = "Al-Qadr", nameFr = "La Destinée", ayahCount = 5, makki = true),
    SurahMeta(number = 98, nameAr = "البينة", nameEn = "Al-Bayyinah", nameFr = "La Preuve", ayahCount = 8, makki = false),
    SurahMeta(number = 99, nameAr = "الزلزلة", nameEn = "Az-Zalzalah", nameFr = "La Secousse", ayahCount = 8, makki = false),
    SurahMeta(number = 100, nameAr = "العاديات", nameEn = "Al-‘Adiyat", nameFr = "Les Coursiers", ayahCount = 11, makki = true),
    SurahMeta(number = 101, nameAr = "القارعة", nameEn = "Al-Qari‘ah", nameFr = "Le Fracas", ayahCount = 11, makki = true),
    SurahMeta(number = 102, nameAr = "التكاثر", nameEn = "At-Takathur", nameFr = "La Course aux richesses", ayahCount = 8, makki = true),
    SurahMeta(number = 103, nameAr = "العصر", nameEn = "Al-‘Asr", nameFr = "Le Temps", ayahCount = 3, makki = true),
    SurahMeta(number = 104, nameAr = "الهمزة", nameEn = "Al-Humazah", nameFr = "Le Calomniateur", ayahCount = 9, makki = true),
    SurahMeta(number = 105, nameAr = "الفيل", nameEn = "Al-Fil", nameFr = "L’Éléphant", ayahCount = 5, makki = true),
    SurahMeta(number = 106, nameAr = "قريش", nameEn = "Quraysh", nameFr = "Quraysh", ayahCount = 4, makki = true),
    SurahMeta(number = 107, nameAr = "الماعون", nameEn = "Al-Ma‘un", nameFr = "L’Ustensile", ayahCount = 7, makki = true),
    SurahMeta(number = 108, nameAr = "الكوثر", nameEn = "Al-Kawthar", nameFr = "L’Abondance", ayahCount = 3, makki = true),
    SurahMeta(number = 109, nameAr = "الكافرون", nameEn = "Al-Kafirun", nameFr = "Les Infidèles", ayahCount = 6, makki = true),
    SurahMeta(number = 110, nameAr = "النصر", nameEn = "An-Nasr", nameFr = "Le Secours", ayahCount = 3, makki = false),
    SurahMeta(number = 111, nameAr = "المسد", nameEn = "Al-Masad", nameFr = "Les Fibres", ayahCount = 5, makki = true),
    SurahMeta(number = 112, nameAr = "الإخلاص", nameEn = "Al-Ikhlas", nameFr = "Le Monothéisme pur", ayahCount = 4, makki = true),
    SurahMeta(number = 113, nameAr = "الفلق", nameEn = "Al-Falaq", nameFr = "L’Aube naissante", ayahCount = 5, makki = true),
    SurahMeta(number = 114, nameAr = "الناس", nameEn = "An-Nas", nameFr = "Les Hommes", ayahCount = 6, makki = true),
)
